services:
  - name: airflow-webserver
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_ADMIN_USER
        sync: false
      - key: AIRFLOW_ADMIN_PASSWORD
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow webserver"
      - key: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
        value: "$PORT"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: airflow-redis
          type: redis
          property: connectionString

  - name: airflow-scheduler
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow scheduler"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: airflow-redis
          type: redis
          property: connectionString

  - name: airflow-worker
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow celery worker"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: airflow-redis
          type: redis
          property: connectionString

  - name: airflow-redis
    type: redis
    plan: starter  # Puedes usar "free" si lo prefieres

databases:
  - name: airflow-db
    plan: standard