services:
  - name: airflow-webserver
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_ADMIN_USER
        sync: false
      - key: AIRFLOW_ADMIN_PASSWORD
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow webserver --port $PORT"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "LocalExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString

  - name: airflow-scheduler
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow scheduler"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "LocalExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString

  - name: airflow-worker
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow tasks run"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "LocalExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString

databases:
  - name: airflow-db
    plan: standard