services:
  - name: airflow-webserver
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: airflow-redis
          property: connectionString
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_ADMIN_USER
        sync: false
      - key: AIRFLOW_ADMIN_PASSWORD
        sync: false
    startCommand: >
      sh -c "airflow db upgrade &&
             airflow users create --username \$AIRFLOW_ADMIN_USER --password \$AIRFLOW_ADMIN_PASSWORD --firstname Admin --lastname User --role Admin --email admin@example.com &&
             airflow webserver"

  - name: airflow-scheduler
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: airflow-redis
          property: connectionString
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
    startCommand: "airflow scheduler"

  - name: airflow-worker
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: airflow-redis
          property: connectionString
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
    startCommand: "airflow celery worker"

databases:
  - name: airflow-db
    engine: postgres
    version: 13
    plan: starter

redis:
  - name: airflow-redis
    plan: free