services:
  - name: airflow-webserver
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_ADMIN_USER
        sync: false
      - key: AIRFLOW_ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: airflow-redis
          type: privateService
          property: host
      - key: REDIS_PORT
        fromService:
          name: airflow-redis
          type: privateService
          property: port
      - key: REDIS_URL
        value: redis://$(REDIS_HOST):$(REDIS_PORT)/0

  - name: airflow-scheduler
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: airflow-redis
          type: privateService
          property: host
      - key: REDIS_PORT
        fromService:
          name: airflow-redis
          type: privateService
          property: port
      - key: REDIS_URL
        value: redis://$(REDIS_HOST):$(REDIS_PORT)/0

  - name: airflow-worker
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: airflow-redis
          type: privateService
          property: host
      - key: REDIS_PORT
        fromService:
          name: airflow-redis
          type: privateService
          property: port
      - key: REDIS_URL
        value: redis://$(REDIS_HOST):$(REDIS_PORT)/0

  - name: airflow-redis
    env: docker
    dockerfilePath: ./redis/Dockerfile
    plan: starter

databases:
  - name: airflow-db
    plan: starter