services:
  - name: airflow-webserver
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_ADMIN_USER
        sync: false
      - key: AIRFLOW_ADMIN_PASSWORD
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow webserver --port $PORT"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_URL
        value: "redis://:$REDIS_PASSWORD@$(REDIS_HOST):$(REDIS_PORT)/0"

  - name: airflow-scheduler
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow scheduler"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: airflow-redis
          type: pserv
          property: host
      - key: REDIS_PORT
        fromService:
          name: airflow-redis
          type: pserv
          property: port
      - key: REDIS_URL
        value: "redis://:$REDIS_PASSWORD@$(REDIS_HOST):$(REDIS_PORT)/0"

  - name: airflow-worker
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: AIRFLOW__CORE__FERNET_KEY
        sync: false
      - key: AIRFLOW_COMMAND
        value: "airflow celery worker"
      - key: AIRFLOW__CORE__EXECUTOR
        value: "CeleryExecutor"
      - key: DATABASE_URL
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
        fromDatabase:
          name: airflow-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: airflow-redis
          type: pserv
          property: host
      - key: REDIS_PORT
        fromService:
          name: airflow-redis
          type: pserv
          property: port
      - key: REDIS_URL
        value: "redis://:$REDIS_PASSWORD@$(REDIS_HOST):$(REDIS_PORT)/0"

  - name: airflow-redis
    type: pserv
    env: docker
    buildCommand: "docker build -t airflow-redis ."
    dockerfilePath: ./redis/Dockerfile
    plan: starter  # Puedes usar "free" si lo prefieres
    envVars:
      - key: REDIS_PASSWORD
        sync: false
    dockerCommand: ["redis-server", "/usr/local/etc/redis/redis.conf"]

databases:
  - name: airflow-db
    plan: standard